version: '3.4'

services:
  codeexecutorservice:
    image: ${DOCKER_REGISTRY-}codeexecutorservice
    build:
      context: .
      dockerfile: CodeExecutorService/Dockerfile

  python-slave:
    image: python-slave
    build:
      context: ./CompilerContainer
      dockerfile: Python.Dockerfile
    volumes:
      - ./CompilerContainer/Keys:/config/.ssh
      - ./CompilerContainer/SourceCode:/config/sourcecode
    restart: always
   
  java-slave:
    image: java-slave
    build:
      context: ./CompilerContainer
      dockerfile: Java.Dockerfile
    volumes:
      - ./CompilerContainer/Keys:/config/.ssh
      - ./CompilerContainer/SourceCode:/config/sourcecode
    restart: always
       